const systems=[
{id:"nervioso",icon:"🧠",name:"Nervioso",short:"Coordina respuestas y procesa información.",role:"Recibe información, la procesa y coordina respuestas mediante el cerebro, la médula espinal y los nervios.",parts:["Encéfalo","Médula espinal","Nervios"],connect:"Se relaciona con todos los sistemas para coordinar sus funciones.",fact:"Los impulsos nerviosos permiten respuestas rápidas ante estímulos."},
{id:"respiratorio",icon:"🫁",name:"Respiratorio",short:"Intercambia oxígeno y dióxido de carbono.",role:"Permite incorporar oxígeno al organismo y eliminar dióxido de carbono mediante el intercambio de gases.",parts:["Nariz y vías respiratorias","Tráquea","Pulmones"],connect:"Trabaja con el circulatorio para llevar oxígeno a las células.",fact:"En los alvéolos ocurre el intercambio de gases entre el aire y la sangre."},
{id:"circulatorio",icon:"❤️",name:"Circulatorio",short:"Transporta sustancias por todo el cuerpo.",role:"Mueve sangre para distribuir oxígeno, nutrientes y hormonas y recoger sustancias de desecho.",parts:["Corazón","Vasos sanguíneos","Sangre"],connect:"Recibe oxígeno del sistema respiratorio y nutrientes del digestivo.",fact:"El corazón impulsa la sangre a través de una red de vasos sanguíneos."},
{id:"digestivo",icon:"🥗",name:"Digestivo",short:"Transforma alimentos en nutrientes.",role:"Descompone los alimentos y permite absorber nutrientes y agua que el organismo necesita.",parts:["Boca","Estómago","Intestino delgado"],connect:"Los nutrientes absorbidos pasan a la sangre para llegar a las células.",fact:"La mayor parte de la absorción de nutrientes ocurre en el intestino delgado."},
{id:"muscular",icon:"💪",name:"Muscular",short:"Produce movimiento y ayuda a mantener la postura.",role:"Los músculos se contraen para producir movimiento, mantener la postura y generar calor.",parts:["Músculos esqueléticos","Músculo cardíaco","Músculo liso"],connect:"Recibe órdenes del sistema nervioso y depende del oxígeno y nutrientes.",fact:"El músculo cardíaco se contrae de forma rítmica para impulsar la sangre."},
{id:"esqueletico",icon:"🦴",name:"Esquelético",short:"Sostiene, protege y permite el movimiento.",role:"Forma el soporte del cuerpo, protege órganos internos y, junto con los músculos, permite el movimiento.",parts:["Huesos","Articulaciones","Cartílagos"],connect:"Forma una unidad funcional con el sistema muscular.",fact:"La médula ósea participa en la formación de células sanguíneas."},
{id:"excretor",icon:"💧",name:"Excretor",short:"Elimina desechos y regula el equilibrio interno.",role:"Elimina productos de desecho y contribuye a regular agua, sales y otras condiciones internas.",parts:["Riñones","Uréteres","Vejiga"],connect:"Filtra la sangre y trabaja con otros sistemas para mantener la homeostasis.",fact:"Los riñones filtran la sangre y producen la orina."},
{id:"endocrino",icon:"⚗️",name:"Endocrino",short:"Regula procesos mediante hormonas.",role:"Produce hormonas que ayudan a regular crecimiento, metabolismo, reproducción y otras funciones.",parts:["Hipófisis","Tiroides","Páncreas"],connect:"Sus hormonas actúan sobre órganos y tejidos de diferentes sistemas.",fact:"Las hormonas son mensajeros químicos que viajan por la sangre."}
];
const cards=document.querySelector("#cards"),detail=document.querySelector("#detail"),content=document.querySelector("#detail-content"),progress=document.querySelector("#progress");let explored=new Set();
cards.innerHTML=systems.map(s=>`<article class="card" tabindex="0" data-id="${s.id}"><div class="icon">${s.icon}</div><h3>Sistema ${s.name}</h3><p>${s.short}</p><span class="tag">Explorar</span></article>`).join("");
function show(id){const s=systems.find(x=>x.id===id);explored.add(id);progress.textContent=`${explored.size}/8 explorados`;content.innerHTML=`<button class="close" onclick="detail.classList.add('hidden')">Cerrar</button><p class="eyebrow">${s.icon} SISTEMA ${s.name.toUpperCase()}</p><h2>¿Qué hace?</h2><div class="detail-grid"><div><p>${s.role}</p><h3>Partes principales</h3><ul>${s.parts.map(p=>`<li>${p}</li>`).join("")}</ul><h3>¿Con quién trabaja?</h3><p>${s.connect}</p></div><aside class="facts"><strong>Dato para recordar</strong><p>${s.fact}</p></aside></div>`;detail.classList.remove('hidden');detail.scrollIntoView({behavior:"smooth",block:"center"})}
cards.addEventListener("click",e=>{const c=e.target.closest(".card");if(c)show(c.dataset.id)});document.querySelector("#start").onclick=()=>document.querySelector("#cards").scrollIntoView({behavior:"smooth"});
const quiz=document.querySelector("#quiz"),answers=["Respiratorio y circulatorio","Digestivo y excretor","Nervioso, muscular, respiratorio y circulatorio","Solo muscular"];quiz.innerHTML=`<h3>¿Cuáles participan directamente cuando corres?</h3><div class="options">${answers.map((a,i)=>`<button class="option" data-i="${i}">${a}</button>`).join("")}</div><div id="feedback" class="feedback"></div>`;
quiz.addEventListener("click",e=>{if(!e.target.classList.contains("option"))return;document.querySelectorAll(".option").forEach(x=>x.classList.remove("selected"));e.target.classList.add("selected");const f=document.querySelector("#feedback");if(e.target.dataset.i==="2"){f.className="feedback correct";f.textContent="✓ Correcto. El movimiento requiere coordinación nerviosa y muscular, y mayor aporte de oxígeno y transporte de sustancias."; }else{f.className="feedback wrong";f.textContent="Pista: piensa en coordinación, movimiento, oxígeno y transporte de sustancias.";}});